name: responsiveworks-website
services:
  - name: web
    github:
      repo: responsiveworks/www-responsiveworks-com
      branch: master
      deploy_on_push: true
    build_command: npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
